name: Multiple Machine Runs
run-name: ${{ github.actor }} Multiple Machines run
on: [workflow_dispatch]
jobs:
  cypress-run:
    example_matrix:
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest , macos-latest]
          version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4